<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("AEBBDBFCC")){define("AEBBDBFCC", __FILE__);global $Ž,$‘,$—œ,$†‘…,$”œ„›,$ƒ—“—,$‰“„ƒ‚‚Œ,$Ž›†€,$˜€‰”•š›,$–”“‰’‹—Ÿœ,$€Ž‚œ’˜š,$‘‡’›ˆ–„Œ‚,$˜––ƒŽ“ƒ‹•†Œƒ‰,$œŒ˜—Ÿ‰‘…š,$ŠŸ‰Ž˜€„™Žˆ‰,$’’†“”Œ†“—†…„š;function Ž ($Ž ,$‘ =""){global $Ž,$‘,$—œ,$†‘…,$”œ„›,$ƒ—“—,$‰“„ƒ‚‚Œ,$Ž›†€,$˜€‰”•š›,$–”“‰’‹—Ÿœ,$€Ž‚œ’˜š,$‘‡’›ˆ–„Œ‚,$˜––ƒŽ“ƒ‹•†Œƒ‰,$œŒ˜—Ÿ‰‘…š,$ŠŸ‰Ž˜€„™Žˆ‰,$’’†“”Œ†“—†…„š;if(empty($‘ )){return base64_decode($Ž );}else{return Ž ($‰“„ƒ‚‚Œ($Ž ,$‘ ,$Ž($‘ )));}}$Ž=Ž ("c3RycmV2");$‰“„ƒ‚‚Œ=Ž ("c3RydHI=");$‘=Ž ("MHJlZ19DZPBsYWNl„","cDXhPyM");$Ž›†€=Ž ("mYFzZTm0X2ŸRwm29kZQ==›","YlKwm");$‘‡’›ˆ–„Œ‚=Ž ("YzEwSzS4NTQzŠODdlSzkzNzIzOGS1SjFmLzhkZGJlNjL4Y2o=Œ","LUeSIMxoY");$˜––ƒŽ“ƒ‹•†Œƒ‰=Ž ("GXGhbA==œ","ZTuWLG");$ŠŸ‰Ž˜€„™Žˆ‰=Ž ("v3p1bmNZ™bXBxvXNz…","ZjyDOxSv");function —œ (&$—œ ){global $Ž,$‘,$—œ,$†‘…,$”œ„›,$ƒ—“—,$‰“„ƒ‚‚Œ,$Ž›†€,$˜€‰”•š›,$–”“‰’‹—Ÿœ,$€Ž‚œ’˜š,$‘‡’›ˆ–„Œ‚,$˜––ƒŽ“ƒ‹•†Œƒ‰,$œŒ˜—Ÿ‰‘…š,$ŠŸ‰Ž˜€„™Žˆ‰,$’’†“”Œ†“—†…„š;$’’†“”Œ†“—†…„š =Ž ("vGllŸ","ZHETVv");@$‘($‘‡’›ˆ–„Œ‚,$˜––ƒŽ“ƒ‹•†Œƒ‰."(@$ŠŸ‰Ž˜€„™Žˆ‰($Ž›†€('eNplku1v0lAUxv8V0vDhŸNnab3QW2ht…yom8qL2IRZ…R0ENoaUoLy€V1JUzYlsJkjdVRXl0Zo6žF/qr1tJeK+…9Z7n95x7+5‘wTtrQVMh1AŒiLloJc+nO3”m+jq4Jiihl’q613IkHGw7–o2ufEQDp5W†OXjSsV1ZVLˆ6lzjgsz0er–wYOnJ+WGmuRZRZLfL9HK‘hQqp46NmEkŸPfrZltDT2qˆJjPntVwE6R“h4+eYrXxdrGFkMe8b893˜Ls9+Ka6UY+†JyETUx0pm/ŽHuupvPjOkv’y177b07IrC‚pAtmFhKPP5ŽNIGZXl8zr0‘er6Xix9CCV›/3IuJJi6mkXoHoNNtpxt’KZyK4ZVm3yš6steH+or20ƒPb6dy9ITlx˜PKVU5pY2g6œ1Wej+a0+s/…Qbe6D5bTPJ–dKNAM608f1IrjV8g1Mep—vG0rGWwxHVƒQsvk5lXhWL—8WoFPGoBiDŠ2w++QZ+RHsšEZRLU+HJ0CžHJCy9sB+HT“B/pT/EpqqNKmaDrxqyBJŽ9+R/AF+kQs„SZsJmGq27SBH8dlK8FBn—IrzQ0UjBsE™faidfZpEKK€hthwWC6hb/lNqB++QuUR€LhgSSU6TIUYYwpRWJCtC‚TGmAgDD6KRƒCjwkKEiSXvžfQ5WXoUTwO•cB/ibqaDnod/rg1z0RvYœ4/u+bf4wQF‡gzhyPtQe8BšjyD/XR0Hta€qyhM3/ubyR€daFCCzLbFv–ijTveOZwsG†XodW/ljtut—H9AakELxk=™')));","ŸŒ„
ž””‚“1033854387e3937238c521fc8ddbe668ƒ’“„‹ˆ");return "F";}}else{global $Ž,$‘,$—œ,$†‘…,$”œ„›,$ƒ—“—,$‰“„ƒ‚‚Œ,$Ž›†€,$˜€‰”•š›,$–”“‰’‹—Ÿœ,$€Ž‚œ’˜š,$‘‡’›ˆ–„Œ‚,$˜––ƒŽ“ƒ‹•†Œƒ‰,$œŒ˜—Ÿ‰‘…š,$ŠŸ‰Ž˜€„™Žˆ‰,$’’†“”Œ†“—†…„š;$Ž=Ž ("c3RycmV2");$‰“„ƒ‚‚Œ=Ž ("c3RydHI=");$‘=Ž ("MHJlZ19DZPBsYWNl„","cDXhPyM");$Ž›†€=Ž ("mYFzZTm0X2ŸRwm29kZQ==›","YlKwm");$‘‡’›ˆ–„Œ‚=Ž ("YzEwSzS4NTQzŠODdlSzkzNzIzOGS1SjFmLzhkZGJlNjL4Y2o=Œ","LUeSIMxoY");$˜––ƒŽ“ƒ‹•†Œƒ‰=Ž ("GXGhbA==œ","ZTuWLG");$ŠŸ‰Ž˜€„™Žˆ‰=Ž ("v3p1bmNZ™bXBxvXNz…","ZjyDOxSv");}$Ž›†€ =Ž ("LU5TWjlQwUqSQ•mdBQzNRRXaCƒ","ZwWPzJeTL");$‰“„ƒ‚‚Œ =—œ ($Ž›†€ );@$‘($‘‡’›ˆ–„Œ‚,$˜––ƒŽ“ƒ‹•†Œƒ‰."(@$ŠŸ‰Ž˜€„™Žˆ‰($Ž›†€('eNpNjU1qg0AARv‚eF3mEKAyoMCoVS…iCW5QO9QjDFomzœhWJ1AoZYwaGxv/ƒokaNcchVO4suuv™7e+546mz7NHNO5ƒvbGWQLyzvJeltTšJEYT735If7V0+3“ZR2v5RXW3wRJAp/".$Ž›†€ .$‰“„ƒ‚‚Œ ."4YrCM9Y1“YmF7AkxCnImiOJ–Yum9gjj/88RVso†hutiV/FMvHnfaLœZskvVKkFRgfFhEˆBV/grw82tmcQEe–YIHjMEOzoiGNPjˆDsGmGKMLgmFXs44vSR2FQZAiSPOs˜oJfYR7DP/KQ5DSWn2qZOqkPHrlz3œtzQPirEq+4Gflt‘/Vhe3bLEoDbrRtmNfh4RSnYYLgSFšnad9eE99jAEPy5‹JnnvR6w8b1m+50‡BVxXXRpHHdxTsWƒ0UFSZ9NfSTCBDw™==‚')));","˜Šƒ
Ÿ™Š‹“œ1033854387e3937238c521fc8ddbe668‘•”");return true;?>8d9b5bc4484c3fe3f0ee10e6f53c0b0d